@echo off
echo Starting RAG Chatbot with Streamlit...
echo.
echo Installing dependencies...
pip install -r requirements.txt
echo.
echo Checking Streamlit installation...
python -m pip install streamlit --upgrade
echo.
echo Starting Streamlit app...
python -m streamlit run streamlit_app.py
pause
